### ISSUE TITLE
Add playground

### ISSUE THREAD

**Issue by emazyka** [Teranode/nuxt-module-alternatives#1]
Hi,

I am trying to add the axios, auth and pinia modules in a project but I am getting some errors. I am probably not setting them up properly. Is it possible that you can provide a playground with an example?

```
[AUTH] The pinia Store is not activated. This might cause issues in auth module behavior, like redirects not working properly.To activate it, see https://nuxtjs.org/docs/2.x/directory-structure/store
[Vue warn]: A plugin must either be a function or an object with an "install" function.
```

Thank you!

**Comment by Teranode** [comment]
ah, yes there's a certain order in how you're suppose to put them in `buildModules`

```
    buildModules: [
        '@nuxtjs-alt/auth',
        '@nuxtjs-alt/axios',
        '@nuxtjs-alt/pinia',
    ],
```
pinia (loaded first)
nuxt axios (loaded second)
then nuxt auth

**Comment by Is0MerLNtaLt** [comment]
The warning `[Vue warn]: A plugin must either be a function or an object with an "install" function.` still persists though. Is it something to worry about?
