### ISSUE TITLE
Middleware is not ignored with meta auth: false

### ISSUE THREAD

**Issue by edupuySportiw** [Teranode/nuxt-module-alternatives#105]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-rc.12`
- Nitro Version:    `0.6.0`
- Package Manager:  `pnpm@7.14.0`
- Builder:          `vite`
- User Config:      `srcDir`, `typescript`, `build`, `vite`, `modules`, `publicRuntimeConfig`, `http`, `auth`, `unocss`, `googleFonts`, `intlify`
- Runtime Modules:  `@nuxtjs-alt/auth@2.0.26`, `@nuxtjs-alt/http@1.3.20`, `@nuxtjs-alt/proxy@1.3.8`, `@pinia/nuxt@0.4.3`, `@unocss/nuxt@0.46.0`, `@intlify/nuxt3@0.2.4`, `nuxt-svgo@1.0.1`, `@nuxtjs/google-fonts@3.0.0-0`
- Build Modules:    `-`

### Reproduction

Activate global middleware in nuxt.config.ts : 
`auth: {
    globalMiddleware: true,
    ...
}`

Define page meta to false : 
`definePageMeta({
    auth: false,
  });
`

When I go to that page, I am still redirected to login page.

### Describe the bug

When i add the meta `auth: false` to a page, I should be able to go to that page even if I'm not logged in.

The issue started when I updated the package to version `2.0.23`. Versions prior to this one are working as expected.

I think the issue is coming from this modification in middleware.ts : 
![image](https://user-images.githubusercontent.com/100761976/197732147-d64722ed-044a-42f6-a67c-b6b60abc6ecf.png)

When I add the meta `auth: false`, `to.meta.auth` is false and therefore, the middleware is not ignored.

**Comment by Teranode** [comment]
can you try the version i pushed out?

**Comment by edupuySportiw** [comment]
It works again, thank you !
