### ISSUE TITLE
Google Oauth

### ISSUE THREAD

**Issue by agracia-foticos** [Teranode/nuxt-module-alternatives#108]
### Environment

- Operating System: `Linux`
- Node Version:     `v18.11.0`
- Nuxt Version:     `3.0.0-rc.12`
- Nitro Version:    `0.6.0`
- Package Manager:  `npm@8.19.2`
- Builder:          `vite`
- User Config:      `srcDir`, `modules`, `compilerOptions`, `vue`, `vite`, `telemetry`, `algolia`, `head`, `auth`, `css`, `build`, `runtimeConfig`
- Runtime Modules:  `genesis-design-system/nuxt`, `@nuxtjs/tailwindcss@5.3.5`, `@nuxtjs/algolia@1.1.4`, `@nuxtjs-alt/auth@2.0.20`, `@nuxtjs/device@3.0.0`, `unplugin-icons/nuxt`, `@pinia/nuxt@0.4.3`, `@nuxtjs/i18n@8.0.0-alpha.3`
- Build Modules:    `-`

### Reproduction

we are implementing authentication and despite the fact that we enter Google, we authenticate ourselves and it returns us correctly to the web, we cannot access the nuxt.config.ts endpoints

![image](https://user-images.githubusercontent.com/77386602/198232698-3de01a52-17f2-4a1c-bbe4-50167277f512.png)

We have forced the token and the userInfo to incorrect values ​​to see if an error was thrown somewhere, but nothing, it doesn't happen there...

What can be happening?

La cookie además se setea correctamente
![image](https://user-images.githubusercontent.com/77386602/198232926-4c033d96-382e-4106-9c46-30ad5ff2dbcc.png)

### Describe the bug

we are implementing authentication and despite the fact that we enter Google, we authenticate ourselves and it returns us correctly to the web, we cannot access the nuxt.config.ts endpoints

![image](https://user-images.githubusercontent.com/77386602/198232698-3de01a52-17f2-4a1c-bbe4-50167277f512.png)

We have forced the token and the userInfo to incorrect values ​​to see if an error was thrown somewhere, but nothing, it doesn't happen there...

What can be happening?

La cookie además se setea correctamente
![image](https://user-images.githubusercontent.com/77386602/198232926-4c033d96-382e-4106-9c46-30ad5ff2dbcc.png)

**Comment by Teranode** [comment]
your environment section says that you do not have `@nuxtjs-alt/http` installed. You need to use that module for the auth module to function.

**Comment by agracia-foticos** [comment]
It seems that you are already answering me, but I have a question:

token: 'http://localhost:3000/login/google/token', 
userInfo: 'http://localhost:3000/login/google/user/'

These two enpoints must be "server route api"? Or pages.vue?

**Comment by Teranode** [comment]
I do not understand your question

**Comment by agracia-foticos** [comment]
I'm trying to collect the Google OAuth information, but I don't see where the object with the information of the name, user, etc...

![image](https://user-images.githubusercontent.com/77386602/198586783-869ff4bd-a9b0-4dcf-b289-d441d26b3f74.png)

I do not see in any of these objects the way to retrieve the data of the user from Google

In fact, this auth._token.google object is an html, which is curious to me, hence the doubt that perhaps those endpoints are returning html because they are really "page" objects (inside the pages folder)

**Comment by Teranode** [comment]
can you try version 2.0.30 to see if you're still getting the same issue?

**Comment by agracia-foticos** [comment]
With 2.0.30 same issue

![image](https://user-images.githubusercontent.com/77386602/199450062-05ded565-7716-4b28-9d8b-7b4c34fa7c04.png)

![image](https://user-images.githubusercontent.com/77386602/199450160-e280e121-31ee-4c03-9660-86ee4360b296.png)

I don't see where is the object with the info (email, name, etc) received from Google Oauth

- Operating System: `Linux`
- Node Version:     `v18.11.0`
- Nuxt Version:     `3.0.0-rc.12`
- Nitro Version:    `0.6.0`
- Package Manager:  `npm@8.19.2`
- Builder:          `vite`
- User Config:      `srcDir`, `modules`, `compilerOptions`, `vue`, `vite`, `telemetry`, `algolia`, `head`, `auth`, `css`, `build`, `runtimeConfig`
- Runtime Modules:  `genesis-design-system/nuxt`, `@nuxtjs/tailwindcss@5.3.5`, `@nuxtjs/algolia@1.1.4`, `@nuxtjs-alt/auth@2.0.30`, `@nuxtjs-alt/http@1.4.2`, `@nuxtjs/device@3.0.0`, `unplugin-icons/nuxt`, `@pinia/nuxt@0.4.3`, `@nuxtjs/i18n@8.0.0-beta.2`
- Build Modules:    `-`

**Comment by Maxp777** [comment]
auth_token: Bearer <!DOCTYPE html> is the html of 404 nuxt page?

**Comment by agracia-foticos** [comment]
> auth_token: Bearer is the html of 404 nuxt page? I seen that token with local strategy when I do something wrong, don't remember what

The endpoints you use are vue page paths, or are they API server paths?
Currently they are pages, but perhaps they should be API routes so that the HTML code of the layout is not injected

**Comment by Maxp777** [comment]
It was nitro server paths. 
But I get that error when I modify Teranode http module to use $fetch, and I do something wrong. 
After I correct the error in module.
I don't remember that I do.
And after Teranode release http with $fetch and i use it now.

**Comment by Maxp777** [comment]
May be I will play with google oauth in next days. And will see how it work.
