### ISSUE TITLE
Sanctum strategy doesn't work

### ISSUE THREAD

**Issue by moonofmylife** [Teranode/nuxt-module-alternatives#11]
Hi! I get the following error
`Cannot destructure property 'url' of 'strategy' as it is undefined.`

I think the problem is that

1. In this line, we give the strategy settings the first and only parameter: [click](https://github.com/Teranode/nuxt-module-alternatives/blob/master/%40nuxtjs-alt/auth/src/resolve.ts#L61)
2. But here we expect the next instance to be the first parameter, and the strategy settings to be the second parameter: [click](https://github.com/Teranode/nuxt-module-alternatives/blob/master/%40nuxtjs-alt/auth/src/providers/laravel-sanctum.ts#L18)

**Comment by Teranode** [comment]
@moonofmylife can you try the update I pushed?

**Comment by Teranode** [comment]
currently working on types, I normally disable typing

**Comment by Teranode** [comment]
@moonofmylife not sure if the update I added will do the trick (for Auth)
