### ISSUE TITLE
$fetch post/patch not using authorization header

### ISSUE THREAD

**Issue by lowbits** [Teranode/nuxt-module-alternatives#112]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.17.0`
- Nuxt Version:     `3.0.0-rc.13`
- Nitro Version:    `0.6.1`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `app`, `runtimeConfig`, `modules`, `css`, `auth`, `image`, `proxy`, `http`, `build`
- Runtime Modules:  `@nuxtjs/tailwindcss@6.1.3`, `@nuxtjs-alt/auth@2.0.30`, `@nuxtjs-alt/http@1.4.2`, `@nuxtjs-alt/proxy@2.0.4`, `@pinia/nuxt@0.3.1`, `@storyblok/nuxt@4.4.2`, `@nuxt/image-edge@1.0.0-27769790.4b27db3`, `@nuxtjs/i18n@8.0.0-beta.3`
- Build Modules:    `-`

### Reproduction

```vue
await $fetch("/api/v1/users", {
			method: "PATCH",
			body: {
				gender: gender?.name,
			},
		})
```

```ts
// .nuxt.config.ts

proxy: {
        enableProxy: true,
        proxies: {
            '/api': {
                target: 'http://localhost:4000',
                changeOrigin: true,
                rewrite: (path:string) => {
                    return path.replace(/^\/api/, '')
                }
            },
        },
        fetch: true
    },

    http: {
        debug: true,
        proxyHeaders: true,
        interceptorPlugin: true,
    },
```

### Describe the bug

when is use `$fetch()` for a GET request, the authorization header is set but when im using `$fetch('/url', {method: 'POST'})` there is no AUTHORIZATION HEADER in the request, and I get a 401.
Did i miss something?

**Comment by Teranode** [comment]
There isn't enough context for me to know what you're trying to accomplish. You say that there is no authorization header, but are you creating an interceptor with `$fetch` to handle that use case? All I'm seeing is a snippet of fetch being used. Please provide a minimal reproduction.

**Comment by lowbits** [comment]
Hey sorry for bothering you.
I think I found the solution.
So I switch from `$fetch`, to `$http.$patch`, the only problem I have now is $http.$patch is sending a HEADER METHOD 'patch', but the server only accepts 'PATCH', for $http.$post, $put, etc the method is sent as uppercase. Only the patch is not working.

**Comment by Teranode** [comment]
I've updated the http module

**Comment by Maxp777** [comment]
> I've updated the http module

@Teranode that is refered to other methods too?
That problem also is resolved https://github.com/Teranode/nuxt-module-alternatives/issues/106#issuecomment-1291640986?
