### ISSUE TITLE
@nuxtjs-alt/auth: Object.hasOwn is not a function

### ISSUE THREAD

**Issue by ncperng** [Teranode/nuxt-module-alternatives#113]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.14.0`
- Nuxt Version:     `3.0.0-rc.13`
- Nitro Version:    `0.6.1`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `modules`, `auth`
- Runtime Modules:  `@nuxtjs-alt/auth@2.0.30`, `@nuxtjs-alt/http@1.4.2`, `@pinia/nuxt@0.4.3`
- Build Modules:    `-`

### Reproduction

I wrote a simple login from with two inputs (username and password) and a submit button. The submit button invoke an login function like the followings:
```
   await nuxtApp.$auth.loginWith("local", {
      body: {
        username: username.value,
        password: password.value,
      },
    });
```

In my repo show the sample, auth settings in nuxt.config.ts no need to access a real backend. When invoke nuxtApp.$auth.loginWith(), the error shows.

### Describe the bug

First of all, thank you guys' efforts to delivery such an important function.

The bug shows in v2.0.30. While installing old version v2.0.14, @nuxtjs-alt/auth works very well.

### Logs

```shell
app.vue:31 TypeError: Object.hasOwn is not a function
    at auth.mjs?v=ead34cba:70
    at storage.mjs?v=ead34cba:109
    at pinia.mjs:1117
    at Array.forEach (<anonymous>)
    at triggerSubscriptions (pinia.mjs:1116)
    at Proxy.<anonymous> (pinia.mjs:1356)
    at store.<computed> (pinia.mjs:917)
    at Storage.setState (storage.mjs?v=ead34cba:90)
    at Auth.setUser (auth.mjs?v=ead34cba:186)
    at LocalScheme.reset (local.mjs?v=ead34cba:134)
```

**Comment by Teranode** [comment]
updated the npm version, try that one
