### ISSUE TITLE
Issue with redirect callback

### ISSUE THREAD

**Issue by twuncher** [Teranode/nuxt-module-alternatives#115]
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v18.10.0`
- Nuxt Version:     `3.0.0-rc.13`
- Nitro Version:    `0.6.1`
- Package Manager:  `npm@8.19.2`
- Builder:          `vite`
- User Config:      `css`, `runtimeConfig`, `modules`, `auth`
- Runtime Modules:  `@nuxtjs-alt/auth@2.1.0`, `@nuxtjs-alt/http@1.4.5`, `@nuxtjs-alt/proxy@1.3.8`, `@pinia/nuxt@0.4.3`, `@formkit/nuxt@1.0.0-beta.11`, `@nuxt/image-edge@1.0.0-27769790.4b27db3`, `@nuxtjs/tailwindcss@6.1.3`    
- Build Modules:    `-`
------------------------------

### Reproduction

I cant really reproduce as it requires a login environment, but the bug is self explanitory.

### Describe the bug

I am using openIDConnect here is my config,

```

 auth: {
    enableMiddleware: true,
    globalMiddleware: false,
    redirect: {
      login: "/",
      logout: "/",
      callback: "/auth",
      home: "/dashboard",
    },
    localStorage: false,
    sessionStorage: false,
    strategies: {
      addopenID: {
        scheme: "openIDConnect",

        endpoints: {
          configuration:
            "https://login.microsoftonline.com/common/v2.0/.well-known/openid-configuration",
        },
        idToken: {
          property: "id_token",
          maxAge: 60 * 60 * 24 * 30,
          prefix: "_id_token.",
          expirationPrefix: "_id_token_expiration.",
        },
        responseType: "code",
        grantType: "authorization_code",
        scope: "openid profile offline_access User.Read",
        codeChallengeMethod: "S256",
        clientId: process.env.AZURE_APPLICATION_ID,
        clientWindow: false,
      },}

When logging in the redirect URL is going to http://localhost:3000///auth which is not a valid url - it seems to be a problem with the encoding?

it should be http://localhost:3000/auth



### Additional context

_No response_

### Logs

_No response_

**Comment by Teranode** [comment]
update your auth module
