### ISSUE TITLE
auth 2.1.2 --> ignores  baseURL

### ISSUE THREAD

**Issue by steklopod** [Teranode/nuxt-module-alternatives#116]
### Environment

- Operating System: `Darwin`
- Node Version:     `v19.0.1`
- Nuxt Version:     `3.0.0-rc.13`
- Nitro Version:    `0.6.1`
- Package Manager:  `npm@8.19.2`
- Builder:          `vite`
- User Config:      `ssr`, `runtimeConfig`, `build`, `css`, `modules`, `http`, `auth`, `app`
- Runtime Modules:  `unplugin-icons/nuxt`, `@pinia/nuxt@0.4.3`, `@nuxtjs-alt/auth@2.1.2`, `@nuxtjs-alt/http@1.4.5`, `@nuxtjs-alt/axios@1.0.19`, 
**@nuxtjs-alt/proxy@1.3.5**
- Build Modules:    `-`

### Reproduction

upgrade to `@nuxtjs-alt/auth": "^2.1.2"

Run
```js
await useAuth().loginWith('local', { body: userPrincipal }) 
```

when

```js
  http: { baseURL: 'https://host.com/api' }
```

### Describe the bug

I upgraded to `@nuxtjs-alt/auth": "^2.1.2"

<img width="717" alt="Снимок экрана 2022-11-11 в 17 59 36" src="https://user-images.githubusercontent.com/29500153/201391293-b9d898df-a81a-45e3-9a75-50cfcf15a5c0.png">
and now 

```js
await useAuth().loginWith('local', { body: userPrincipal }) 
```
ignores `http: { baseURL` from `nuxt.config` by replacing it with `localhost:3000`

<img width="605" alt="Снимок экрана 2022-11-11 в 16 43 53" src="https://user-images.githubusercontent.com/29500153/201375115-a5390f91-b184-4dc9-af9f-547969cb35e7.png">

<img width="291" alt="Снимок экрана 2022-11-11 в 16 44 16" src="https://user-images.githubusercontent.com/29500153/201375180-47e67a83-e67c-49e5-b662-cc47ff384ad1.png">

<img width="530" alt="Снимок экрана 2022-11-11 в 16 50 30" src="https://user-images.githubusercontent.com/29500153/201376533-49bb6aea-715b-4afe-a040-9b4a12e2f6ba.png">

**Comment by steklopod** [comment]
Upgrading `"@nuxtjs-alt/proxy": "^2.0.4"` gives an error
<img width="822" alt="Снимок экрана 2022-11-11 в 17 38 12" src="https://user-images.githubusercontent.com/29500153/201387477-eefaa89d-9591-46dd-9f81-f928fe15c2e6.png">
<img width="585" alt="Снимок экрана 2022-11-11 в 17 38 24" src="https://user-images.githubusercontent.com/29500153/201387505-e2d7f698-83f2-4e30-be74-41b2fee75e73.png">

**Comment by Teranode** [comment]
baseURL makes call to the server. You are using `loginWith()` which makes a call via the client side. (when you have ssr enable subsequent calls are made to the server if enabled.)

If you took a look at the http module the module is based off of, then you'd see that there is a `browserBaseURL` for client side handling.
