### ISSUE TITLE
auth+i18n infinite redirect

### ISSUE THREAD

**Issue by Maxp777** [Teranode/nuxt-module-alternatives#122]
### Environment

nuxt 3 edge

### Nuxt Config

https://github.com/Maxp777/nuxt3

### Reproduction

https://github.com/Maxp777/nuxt3

### Describe the bug

That not work now, but worked some time ago
```
import { defineNuxtPlugin } from '#app'

export default defineNuxtPlugin((nuxtApp) => {
  nuxtApp.$auth.onRedirect((to: any) => {
    console.log(nuxtApp.$localePath(to)) // <-----------------------it output infinite times
    return nuxtApp.$localePath(to)
  })
}) 
```

### Additional context

With that work, or is need to return second parameter options as an object like in original module

https://github.com/Teranode/nuxt-module-alternatives/pulls

**Comment by Teranode** [comment]
update your auth module.
