### ISSUE TITLE
`loginWith()` does not redirect

### ISSUE THREAD

**Issue by steklopod** [Teranode/nuxt-module-alternatives#132]
### Environment

```json
 "dependencies": {
    "@nuxtjs-alt/auth": "2.1.6",
    "@nuxtjs-alt/axios": "^1.1.0",
    "@nuxtjs-alt/http": "^1.5.3",
    "@nuxtjs-alt/proxy": "^2.1.0",
    "@pinia/nuxt": "0.4.3",
    "js-cookie": "3.0.1",
    "pinia": "2.0.23",
    "sass": "1.56.1",
    "vuetify": "^3.0.1"
  },
  "devDependencies": {
    "nuxt": "3.0.0"
  }
```

### Nuxt Config

```ts
import { defineNuxtConfig } from 'nuxt/config'

const host = 'https://colaba.online';

export default defineNuxtConfig({
  ssr: true,
  runtimeConfig: {
    public: {
      API_URL: `${host}/api`
    }
  },
  build: {
    transpile: ['vuetify']
  },
  css: ['vuetify/lib/styles/main.sass'],
  modules: [
            '@nuxtjs-alt/auth',
            '@nuxtjs-alt/http',
            '@nuxtjs-alt/proxy', // needed if using ssr
            '@pinia/nuxt'],
  auth: {
    scopeKey: 'scope',
    globalMiddleware: true,
    // fullPathRedirect: false,
    strategies: {
      local: {
        scheme: 'refresh',
        user: { property: false },
        token: {
          property: 'access_token',
          required: true,
          type: 'Bearer',
          maxAge: 60 * 2
        },
        refreshToken: {
          property: 'refresh_token',
          tokenRequired: false,
          maxAge: 60 * 60 * 24 * 21
        },
        endpoints: {
          login: { url: `${host}/api/auth/login`, method: 'post' },
          user: { url: `${host}/api/auth/user`, method: 'post' }
        }
      }
    }
  },
})
```

### Reproduction

Here is a reproduction link:
https://stackblitz.com/edit/nuxt-starter-ykgz8i?file=pages%2Flogin%2Findex.vue,nuxt.config.ts,package.json

Just press `login` button

You can test it from localhost:3000 also.

Existing in backend user already provided. Just press `login` button.

### Describe the bug

Can't log in with strategy `local`

### Logs

```shell
No error logs
```

**Comment by Teranode** [comment]
use:
```ts
modules: [
    '@nuxtjs-alt/auth',
    '@nuxtjs-alt/http',
    '@nuxtjs-alt/proxy',
    '@pinia/nuxt'
],

and try again

**Comment by steklopod** [comment]
<img width="453" alt="Снимок экрана 2022-11-29 в 16 54 29" src="https://user-images.githubusercontent.com/29500153/204578091-abb64a97-6322-4171-9658-32ead6076282.png">
I took it from readme and it's already has such order.


Also do I need `'@nuxtjs-alt/http`,    `'@nuxtjs-alt/proxy'` ?

**Comment by Teranode** [comment]
You had `@pinia/nuxt` mentioned twice in the nuxt config of the original post and in the reproduction.

`@nuxtjs-alt/http` - technically no as I've made it so that if it's not there it will add it for you in a recent update.

`@nuxtjs-alt/proxy` - yes, only if you intend to use SSR otherwise it's not needed, however it has some other functionality that `@nuxtjs-alt/http` uses if you intend to proxy client-side requests like how it does for the server.

**Comment by Teranode** [comment]
I can assure you when I pressed that login button it redirected, besides the `modules` issue, I had changed nothing else.

![](https://i.imgur.com/8f8itQk.gif)

**Comment by steklopod** [comment]
Thank you for your help. Maybe it’s a problem with my browser
