### ISSUE TITLE
TypeError: $fetch.$post is not a function

### ISSUE THREAD

**Issue by Natronick** [Teranode/nuxt-module-alternatives#135]
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.11.0`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `npm@9.1.3`
- Builder:          `vite`
- User Config:      `ssr`, `typescript`, `modules`, `auth`
- Runtime Modules:  `@nuxtjs/tailwindcss@6.1.3`, `@vueuse/nuxt@9.6.0`, `@nuxtjs-alt/auth@2.1.6`, `@nuxtjs-alt/http@1.5.4`, `@nuxtjs-alt/proxy@2.1.2`, `@pinia/nuxt@0.4.6`
- Build Modules:    `-`

### Nuxt Config

  // https://v3.nuxtjs.org/api/configuration/nuxt.config
  export default defineNuxtConfig({
      ssr: true,
      typescript: {
          shim: false,
      },
      modules: [
          '@nuxtjs/tailwindcss',
          '@nuxtjs-alt/auth',
          '@nuxtjs-alt/http',
          '@nuxtjs-alt/proxy',
          '@pinia/nuxt',
      ],
      auth: {
          strategies: {
              github: {
                  clientSecret: 'my_secret', 
                  clientId: 'my_id',
              },
          },
      },
  });

### Reproduction

I can't share my github oauth secrets. I made a very simple nuxt app to try login to github using your module.

### Describe the bug

During the oauth2 code redirect process my nuxt server try to make an api call to retrieve the access token in exchange of the oauth2 code using this call (from src/utils/provider.ts): 
```ts
              $fetch.$post(options.tokenEndpoint, {
                  body: data,
                  headers
              })
              .then((response) => {
                  event.res.end(JSON.stringify(response))
              })
              .catch((error) => {
                  event.res.statusCode = error.response.status
                  event.res.end(JSON.stringify(error.response.data))
              })
```
But it seems that $fetch is not an instance but un function to get the instance.
I've probably misconfigured something but i can't figure out what.

I tried to change `$fetch.$post` by `$fetch().$post` then it worked as expected.

**Comment by Teranode** [comment]
I've updated the auth module.

**Comment by Natronick** [comment]
It works fine, thank you very much!
