### ISSUE TITLE
Nuxt3 plugin error

### ISSUE THREAD

**Issue by moonofmylife** [Teranode/nuxt-module-alternatives#16]
@Teranode Hi! I get the following error after running application:
`Vue warn]: A plugin must either be a function or an object with an "install" function.`

Reason: [click](https://github.com/Teranode/nuxt-module-alternatives/blob/master/%40nuxtjs-alt/auth/src/runtime/templates/auth.plugin.mjs#L24)

![image](https://user-images.githubusercontent.com/46625964/158807281-999dee14-647e-47fb-928a-e678d3c805ee.png)
![image](https://user-images.githubusercontent.com/46625964/158807764-94592694-c8ce-495d-ba7a-8d87a0bed0b3.png)

**Comment by Teranode** [comment]
@moonofmylife update

**Comment by moonofmylife** [comment]
@Teranode yea, fixed.
Thank you <3
