### ISSUE TITLE
Error redirect after login

### ISSUE THREAD

**Issue by 4KDA** [Teranode/nuxt-module-alternatives#19]
With watchLoggedIn = true, after executing loginWith, I login, but I get an error

<img width="593" alt="image" src="https://user-images.githubusercontent.com/38465364/159155470-4d161ff0-09f6-4262-9ac5-06389b39dc4b.png">
<img width="460" alt="image" src="https://user-images.githubusercontent.com/38465364/159155518-433b8d65-1128-44e1-a708-c1add9bf2d49.png">

**Comment by Teranode** [comment]
What scheme and provider are you using?

**Comment by 4KDA** [comment]
> What scheme and provider are you using?

Laravel JWT
<img width="566" alt="image" src="https://user-images.githubusercontent.com/38465364/159184011-16bbfbb9-e273-4881-9ae4-d51e3ceb45e6.png">

**Comment by moonofmylife** [comment]
@Teranode I have the same error after calling loginWith. I'm using nuxt 3 and laravel sanctum provider
![image](https://user-images.githubusercontent.com/46625964/159260333-e598c07c-8289-4bd3-96fb-c23affd74805.png)
![image](https://user-images.githubusercontent.com/46625964/159260403-14bb9525-c8e7-4f5b-9a0f-708ea16f7013.png)

**Comment by Teranode** [comment]
@moonofmylife @4KDA pushed another update try that?
