### ISSUE TITLE
Redirect options for auth module

### ISSUE THREAD

**Issue by skyroses** [Teranode/nuxt-module-alternatives#21]
Hi! Why are there no options for setting up a redirect? By default, the module redirects to the /home page after login. Can this behavior be changed?
![image](https://user-images.githubusercontent.com/46625964/159284328-cdd045e1-cd93-4c68-964a-8fd89aea7876.png)

**Comment by Teranode** [comment]
Not sure as far as I know I haven't touched the redirect params but I'll check it out tomorrow

**Comment by moonofmylife** [comment]
Sorry, I am inattentive, it was cache...
