### ISSUE TITLE
Auth module: laravel sanctum ssr

### ISSUE THREAD

**Issue by skyroses** [Teranode/nuxt-module-alternatives#22]
Hi! I have the following problem going on: if you refresh the page after authorization, the authorization is reset to zero. 

My configuration:
```
  auth: {
    watchLoggedIn: true,
    redirect: {
      login: "/auth/login",
      logout: "/",
      callback: "/auth/login",
      home: "/",
    },
    strategies: {
      laravelSanctum: {
        url: process.env.API_BASE_URL,
        provider: "laravel/sanctum",
        cookie: {
          server: true,
          name: "XSRF-TOKEN",
        },
        endpoints: {
          csrf: {
            url: "/sanctum/csrf-cookie",
          },
          login: {
            url: "/api/auth/users/login",
            method: "post",
          },
          logout: {
            url: "/api/auth/logout",
            method: "post",
          },
          user: {
            url: "/api/auth/me",
            method: "post",
          },
        },
        user: {
          property: {
            client: false,
            server: false,
          },
          autoFetch: true,
        },
      },
    },
  },
```

I added a few logs and found that SSR gets the "CSRF token mismatch" error from the backend, but at the same time everything is fine on the client :)
It is possible that the CSRF token request is not being executed on the server

<hr>

I'm using nuxt 3
auth module version: 1.0.10
laravel version: 9.4.1

**Comment by Teranode** [comment]
You need to use the `nuxtjs-alt/proxy`module to handle requests on the server end or create a api endpoint in `server/api`that handles those requests.

**Comment by moonofmylife** [comment]
I installed and configured the proxy, it didn't help in any way. The problem remains: there is no authorization in the server rendering :)

**Comment by moonofmylife** [comment]
![image](https://user-images.githubusercontent.com/46625964/159470631-6ae840ff-ab36-45ee-8a71-a3550e61b55e.png)

**Comment by moonofmylife** [comment]
Middleware is not working for me because of this problem

**Comment by Teranode** [comment]
I've updated the proxy module update that and tell me if sanctum works now?

**Comment by Teranode** [comment]
closing due to no reply.
