### ISSUE TITLE
How to access Pinia auth store using composable

### ISSUE THREAD

**Issue by andyjamesn** [Teranode/nuxt-module-alternatives#27]
When using Pinia if you have a counter store in stores/counter.js

You can access it in a component 
```javascript
import { useCounterStore } from '@/stores/counter'
const counter = useCounterStore()
```

How do we do the same thing using the auth store data

**Comment by andyjamesn** [comment]
I am not sure if this is correct but I created a file in stores/auth.js

```javascript
import { defineStore } from 'pinia'
export const useAuthStore = defineStore('auth', {

})
```

Now using the following I can access the auth and get users logged in state and user info

```
import { useAuthStore } from '@/stores/auth'
const auth = useAuthStore()
```

Any input or advice would be welcome.

I have succesfully implemented Proxy, Auth and Store in Nuxt3 using nuxt-module-alternatives so thank you for your hard work! :D

**Comment by Teranode** [comment]
@andyjamesn you can get the store via `$auth.$storage.getStore()` now

**Comment by andyjamesn** [comment]
Works perfectly, thanks!
