### ISSUE TITLE
Proxy in latest version cannot work well 

### ISSUE THREAD

**Issue by KahrLu** [Teranode/nuxt-module-alternatives#32]
Hi @Teranode ,I'm sorry, maybe I was wrong just now.
Now my Axios and proxy versions are the latest, but proxy still doesn't work.
![image](https://user-images.githubusercontent.com/76502123/164617874-83b9a245-9dd5-4bc9-bb88-426f323941b8.png)
![image](https://user-images.githubusercontent.com/76502123/164617983-f76659eb-2106-46ae-b850-8e5cc06e3259.png)

[Vue Router warn]: No match found for location with path "/api/v2/Member"

Could you please check on your side?

**Comment by Teranode** [comment]
@KahrLu `http-proxy-middleware` is going through a refactor so im gonna be using `http-proxy` can you update to `1.2.0` and see if that works?

**Comment by KahrLu** [comment]
Thx, it works well now

**Comment by elijah-gauthier** [comment]
Hello, I have same problem here, how did you resolve it please ? I tried @Teranode s answer but it doesn't work.

**Comment by ahoiroman** [comment]
Got the same problem. Would be great so see a working example.
