### ISSUE TITLE
ssrContext is undefined when using the oauth2 scheme

### ISSUE THREAD

**Issue by emazyka** [Teranode/nuxt-module-alternatives#34]
When adding an oauth2 strategy with a proxied endpoint, the token endpoint request results in an error because the 
[ssrContext](https://github.com/Teranode/nuxt-module-alternatives/blob/master/@nuxtjs-alt/auth/dist/runtime/core/auth.mjs#L185) seems to be undefined.

Fyi, I've tested the exact same strategy configuration with a nuxt2 app and it works. The line that results in an error used to be like [this](https://github.com/nuxt-community/auth-module/blob/dev/src/core/auth.ts#L325).

**Comment by Teranode** [comment]
@emazyka i've update the package (not reflected in github) can you try now?

**Comment by Teranode** [comment]
closing due to no reply.
