### ISSUE TITLE
auth module cookie package Vite errors

### ISSUE THREAD

**Issue by DanLeininger** [Teranode/nuxt-module-alternatives#4]
The cookie package in the auth module errs with 
```
Uncaught SyntaxError: The requested module '/_nuxt/node_modules/cookie/index.js?v=7ef19669' does not provide an export named 'default'
```
Seems to be an issue with Vite?
https://github.com/jshttp/cookie/issues/127

I got around this by creating a `utils/cookie.ts` and copying the cookie package into it and then using ESM exports
```javascript
// utils/cookie.ts
...
export const serialize = (name, val, options) => { ...
export const parse = (str, options) => { ...
```

And in `auth/core/storage.ts`:
```javascript
// auth/core/storage.ts
...
import { parse, serialize } from '../utils/cookie'
...
```

Thanks again!

**Comment by Denoder** [comment]
I'll get to fixing that soon, at the moment I'm getting issues related to this: https://github.com/nuxt/nuxt.js/issues/13439 and it's preventing any of the modules from working. (in my use-case since I utitlize all of them)

**Comment by Teranode** [comment]
should be fixed now
