### ISSUE TITLE
Redirect if not logged in triggered too late?

### ISSUE THREAD

**Issue by ahoiroman** [Teranode/nuxt-module-alternatives#43]
Hello everybody,

My Sanctum Auth is working, but I mentioned something strange.

If I got a protected route - e.g. "/dashboard", which contains a component, which does something like this:

```
let id = $auth.user.id;
useFetch(`/api/user/${id}/teams`, {
        server: false,
        credentials: "include",
        headers,
        ...opts,
    });
```

I am getting, if I am hitting "/dashboard" manually,  this message in the browser:

> Redirecting to /auth/signin

<img width="320" alt="Bildschirmfoto 2022-06-02 um 09 30 30@2x" src="https://user-images.githubusercontent.com/23051150/171577532-0b37da89-55a7-461e-81b3-4000ebf118c0.png">

The redirect is not happening, the message just stays the same.

The log tells me this:

> [nuxt] [request error] Cannot read properties of null (reading 'id')

Which points to the api-call:

```
/api/${$auth.user.id}/teams
```

If I edit the `dashboard.vue`, and adding this to the component, which has the api-call in it's `<script setup>`:

```
<TeamCard v-if="$auth.user.isLoggedIn"/>
```

the redirect is processed as expected.

So it seems the middleware does not redirect the unauthenticated user, before the protected route ("/dashboard") and the related page (`dashboard.vue`) is loaded?

**Comment by lowbits** [comment]
Im facing same issue, in my dashboard, if i click logout, the session is destroyed and the user object is empty.
But im staying at the dashboard route, loggedIn says false and user is empty.


Currently im using a workaround: click on logout button uses $auth.logout() and $router.push to index.

**Comment by Teranode** [comment]
what scheme/provider are you guys utilizing?

**Comment by lowbits** [comment]
this is my configuration

use local one because i use a nestjs backend


    ```
auth: {
        //@ts-ignore
        redirect: {
            home: "/home",
            login: "/?open-dialog=signin",
            logout: "/",
        },
        watchLoggedIn: true,
        strategies: {
            //@ts-ignore
            local: {
                url: process.env.API_BASE_URL,
                enabled: true,
                provider: "laravel/jwt",
                token: {
                    property: "token.accessToken",
                    global: true,
                    // required: true,
                    type: "Bearer",
                },
                user: {
                    autoFetch: true,
                },
                endpoints: {
                    login: {url: "/v1/auth/login", method: "post"},
                    logout: {url: "/v1/auth/logout", method: "post"},
                    user: {url: "/v1/auth/me", method: "get"},
                },
            },
        },
```

**Comment by Teranode** [comment]
can you try with the update i pushed?
