### ISSUE TITLE
Example configuration for authentication with Keycloak

### ISSUE THREAD

**Issue by tdoan2010** [Teranode/nuxt-module-alternatives#45]
Hi, could you add an example configuration how to use your `@nuxtjs-alt/auth` with OAuth2, specifically with Keycloak? I tried to configure it like described in [`@nuxtjs/auth-next`](https://auth.nuxtjs.org/schemes/oauth2) but somehow it doesn't work for me. It keeps redirecting me to `/login` path.

I see that you have examples for "Cookie-based auth" and "Laravel Sanctum", but not OAuth2. Is it possible to use your `@nuxtjs-alt/auth` with OAuth2?

**Comment by Teranode** [comment]
I don't know what keycloak is unfortunately, so I wouldn't be of help to provide an example.

Reguarding Oauth2 and other functions of the auth plug-in, I primarily use the cookie based auth which was why I provided extra guidance in the docs. I fix bugs in the auth module if there are enough people nneding a fix or if I have time to. take a look at anything outside of the cookie auth.

**Comment by Caceresenzo** [comment]
I made a pull request (https://github.com/Teranode/nuxt-module-alternatives/pull/57) since there was a bug preventing the module to correctly work. If its accepted, you should be able to do the following to use Keycloak as a scheme.

```typescript
import { defineNuxtConfig } from 'nuxt'

// https://v3.nuxtjs.org/api/configuration/nuxt.config
export default defineNuxtConfig({
  // ...
  auth: {
    pinia: {
      namespace: "auth"
    },
    rewriteRedirects: true,
    fullPathRedirect: false,
    watchLoggedIn: true,
    redirect: {
      login: '/login',
      callback: '/login',
      home: '/',
      logout: '/',
    },
    cookie: {
      prefix: "token",
      options: {
        path: "/",
        secure: true,
      },
    },
    strategies: {
      keycloak: {
        name: "keycloak",
        scheme: "openIDConnect",
        enabled: true,
        endpoints: {
          // either this
          configuration: 'http://localhost:9800/realms/App/.well-known/openid-configuration',
		  
          // or this
          authorization: "http://localhost:9800/realms/App/protocol/openid-connect/auth",
          token: "http://localhost:9800/realms/App/protocol/openid-connect/token",
          userInfo: "http://localhost:9800/realms/App/protocol/openid-connect/userinfo",
          logout: "http://localhost:9800/realms/App/protocol/openid-connect/logout",
        },
        token: {
          property: "access_token",
          type: "Bearer",
          name: "Authorization",
          maxAge: 300,
        },
        refreshToken: {
          property: "refresh_token",
          maxAge: 60 * 60 * 24 * 30,
        },
        idToken: {
          property: "id_token"
        },
        responseType: "code",
        grantType: "authorization_code",
        clientId: "frontend",
        scope: ["openid", "profile", "email"],
        codeChallengeMethod: "S256"
      },
    }
  }
})
```
Of course, replace `http://localhost:9800/` with your Keycloak's URL.

And don't forget to add a web origin to prevent being blocked by CORS:
![image](https://user-images.githubusercontent.com/7386242/182044840-f40bc2a2-8399-4603-a9c2-2fdffaa2a6ff.png)

**Comment by Teranode** [comment]
I've merged it.

**Comment by tdoan2010** [comment]
Thank you very much! I'll try it when I have a chance.
