### ISSUE TITLE
Cannot start nuxt

### ISSUE THREAD

**Issue by desaintflorent** [Teranode/nuxt-module-alternatives#48]
I tried your solution ( proxy and svg-sprite ) but getting an error when starting nuxt in dev mode:

 ``Cannot find module '[...]/node_modules/@nuxtjs-alt/proxy/dist/module.mjs'. Please verify that the package.json has a valid "main" entry``

here my package.json file : 

```
{
	"private": true,
	"scripts": {
		"build": "nuxt build",
		"dev": "nuxt dev",
		"generate": "nuxt generate",
		"preview": "nuxt preview"
	},
	"devDependencies": {
		"@nuxtjs/tailwindcss": "^5.1.3",
		"@tailwindcss/aspect-ratio": "^0.4.0",
		"@tailwindcss/forms": "^0.5.2",
		"@tailwindcss/typography": "^0.5.2",
		"nuxt": "3.0.0-rc.4"
	},
	"dependencies": {
		"@nuxtjs-alt/proxy": "file:modules/@nuxtjs-alt/proxy"
	}
}

```

After ``npm install`` I can see the module in node-modules/@nuxtjs-alt/ . It's an exact copy of nuxt-module-alternatives/@nuxtjs-alt/proxy folder and there is no dist/module.mjs file. 
So what did I do wrong ?

**Comment by Teranode** [comment]
please use the npmjs package if you're not sure on how to use the package locally.
https://www.npmjs.com/package/@nuxtjs-alt/proxy
