### ISSUE TITLE
proxy doesn't work on production

### ISSUE THREAD

**Issue by ironytr** [Teranode/nuxt-module-alternatives#5]
hello, thank you for this packages, im starting to learn nuxt3 thanks to you. proxy module works great on dev mode but not working on production mode. gives "page not found" error when i try to reach my endpoint via proxy. i have freshly installed nuxt3 project after your modules. tried to login my backend (dev works not on production). is there something am i missing with config?

![image](https://user-images.githubusercontent.com/10614686/157327975-3acd8bcf-5079-4ace-b8d5-a70c98dd8cf1.png)
![image](https://user-images.githubusercontent.com/10614686/157328052-5690cecd-4151-4384-ae1c-8fbc35a87b0b.png)
![image](https://user-images.githubusercontent.com/10614686/157328132-80aa418d-06fd-4b38-8d8f-2f9d28ac9cf9.png)

**Comment by Teranode** [comment]
I'm currently trying to work around that, so give me a couple of days to figure that out.

**Comment by Teranode** [comment]
@ironytr go to the proxy directory and read the readme, you can install via npmjs `nuxtjs-alt/proxy` as i've updated it and tell me if that is working for you.

**Comment by ironytr** [comment]
> @ironytr go to the proxy directory and read the readme, you can install via npmjs `nuxtjs-alt/proxy` as i've updated it and tell me if that is working for you.
Hello Tranode, thank you for interest, well now dev and prod both side is gone. first thing i noticed "hpm proxy is rewireted" console.log thing is not appearing with both side.
this missing with new update 
![image](https://user-images.githubusercontent.com/10614686/157671157-c51b0ae4-f6ff-40bc-bba7-e13720cae072.png)


dev mode 
![image](https://user-images.githubusercontent.com/10614686/157670112-45779b2a-cd13-43a4-ac81-70eec41e3a1b.png)

prod mode
![image](https://user-images.githubusercontent.com/10614686/157670763-b867c701-30c8-475a-a196-927c30bc91b7.png)


with new update yarn dev
![image](https://user-images.githubusercontent.com/10614686/157671619-082da390-e78c-485b-ac5e-2b8bbfc5595b.png)

**Comment by ironytr** [comment]
> 
Hello Teranode, tried few times (installed via yarn, downloaded from github put to modules folder, changed order of packages in package.json and nuxt config.) still doesn't work

starting with new clean project yarn dev gives that proxy log and dev mode works but if i build secondary time its not working again
![image](https://user-images.githubusercontent.com/10614686/157846546-7e312daf-1e89-44cc-897b-a8cceb6bc411.png)

after rebuilds with dev this not appearing and proxy doesn't work with dev too.

in prod mode still doesn't work :( i wish i could help you but my js knowledge is not enough

i think to fix this issue proxy rewrite console log should appear with dev and prod when rebuild again.

**Comment by ironytr** [comment]
> If you are using vite than this is most likely related to this issue: [vitejs/vite#3475](https://github.com/vitejs/vite/issues/3475)

Hello @z3cka, yes you are right. now i tried vite version of proxy, developer mode is working but production mode is not working like this package. i looked few of issues at vite, they don't try to fix i guess.

**Comment by Teranode** [comment]
hmm, it's odd, its working for me in production but not dev mode.

**Comment by Teranode** [comment]
@ironytr can you tell me if there is file called `proxy-0.ts` in your `server/proxy` folder?

**Comment by ironytr** [comment]
> @ironytr can you tell me if there is file called `proxy-0.ts` in your `server/proxy` folder?
> 
> Edit: Also pushed another update
@Teranode now proxy is working with both side!!! thank you for your interest. u are a hero without a cape!
![image](https://user-images.githubusercontent.com/10614686/157857672-402ac728-b487-4631-b22b-43a4c7d34086.png)
but now axios bugged >.< why this happening? i guess vite building order is making those errors?
![image](https://user-images.githubusercontent.com/10614686/157857779-ed698218-9004-46c0-a9ce-43d6e7484eee.png)
