### ISSUE TITLE
 Cannot start nuxt:  Cannot find module 

### ISSUE THREAD

**Issue by lowbits** [Teranode/nuxt-module-alternatives#51]
Hey Teranode, thank you I appreciate your work 🤙
After your recent update, removing pinia I cannot start my nuxt application.
Maybe I'm missing something but I tried with yarn and npm.

Both same error

` Cannot start nuxt:  Cannot find module '/Users/lowbots/git/web-app/node_modules/@nuxtjs-alt/auth/dist/module.mjs'. Please verify that the package.json has a valid "main" entry`

with yarn i get this error

`Cannot start nuxt:  Cannot read properties of undefined (reading 'push')  
node_modules/@nuxtjs-alt/auth/dist/module.mjs:614:24
`

**Comment by Teranode** [comment]
are you using nuxt rc.4 or rc.5?

**Comment by lowbits** [comment]
I was using rc.4

**Comment by Teranode** [comment]
use rc.5 the second error pertains to how the middleware is handled.

**Comment by lowbits** [comment]
thank you :)
