### ISSUE TITLE
Disable @nuxtjs-alt/proxy in favor of nuxt-proxy

### ISSUE THREAD

**Issue by nathanchase** [Teranode/nuxt-module-alternatives#52]
I am trying to get a proxy working for axios/useFetch/$fetch, but the server/middleware/@proxy approach you've implemented doesn't seem to work on my production build.

I wanted to try to use https://github.com/wobsoriano/nuxt-proxy, but I'm unable to because the @nuxtjs-alt/auth and @nuxtjs-alt/axios packages in combination with a "proxy" block in my nuxt.config somehow seem to trigger a requirement error:

 ERROR  [unhandledRejection] Cannot find module '@nuxtjs-alt/proxy'

Is @nuxtjs-alt/proxy demanding to be installed because of `proxy` being in nuxt.config? Is there any way to disable that, and disable the auto-creation of the `proxy.ts`?

So, trying to do the following:
```
modules: [
    '@vueuse/nuxt', 
    '@kevinmarrec/nuxt-pwa', 
    '@nuxt/image-edge', 
    '@nuxtjs/device',
    '@nuxtjs/stylelint-module', 
    '@nuxtjs-alt/auth'
    '@nuxtjs-alt/axios', 
    ['@pinia/nuxt', { autoImports: ['defineStore'] }], 
    'nuxt-proxy', 
  ],
```

**Comment by Teranode** [comment]
That is because im following the same code as `nuxt-axios`:
https://github.com/nuxt-community/axios-module/blob/d8c99e5edbd2d8ac7d3abe186dd435922e7e1a31/lib/module.js#L140

and as such I'm not sure If I should disable it in favor of the alternative you suggested. Can you tell me what's happening that has your proxy not working?

**Comment by nathanchase** [comment]
> That is because im following the same code as `nuxt-axios`: https://github.com/nuxt-community/axios-module/blob/d8c99e5edbd2d8ac7d3abe186dd435922e7e1a31/lib/module.js#L140
> 
> and as such I'm not sure If I should disable it in favor of the alternative you suggested. Can you tell me what's happening that has your proxy not working?

I add my baseURL via environment variables, or explicitly in the nuxt.config, and it fails to add that to '/apt' requests in production.

I've verified that production has the environment variables declared correctly, and I've tried all combinations of the following in my nuxt.config, and it only seems to work when running the dev server locally - not on production using `nuxi build` and `nuxi preview`:
```
runtimeConfig: {
    axios: {
      apiBaseUrl: process.env.API_BASE_URL,
    },
    public: {
      axios: {
        apiBaseUrl: process.env.API_BASE_URL,
      },
      apiBaseUrl: process.env.API_BASE_URL,
    },
  },

  vite: {
    server: {
      proxy: {
        '/api': {
          target: process.env.API_BASE_URL,
          secure: false,
          changeOrigin: true,
        },
      },
    },
  },

  axios: {
    proxy: true,
  },

  proxy: {
    options: {
      target: process.env.API_BASE_URL,
      changeOrigin: true,
    },
  },
```

**Comment by Teranode** [comment]
@nathanchase Hmm, I've removed the module requirement from the axios plugin so update and try now.
Also do tell me if what you're trying to do works for you, cause last time there were complaints on fetch not working with proxy due it it not having an intercept for baseUrls, so I wanna know if I should make something for that.

**Comment by nathanchase** [comment]
> @nathanchase Hmm, I've removed the module requirement from the axios plugin so update and try now. Also do tell me if what you're trying to do works for you, cause last time there were complaints on fetch not working with proxy due it it not having an intercept for baseUrls, so I wanna know if I should make something for that.

Thanks! I'll try it and report back soon!

**Comment by nathanchase** [comment]
Well, if I enable the `options.proxy` it just causes the entire Nuxt server to stop working entirely. Localhost can't be found.

**Comment by nathanchase** [comment]
> > Also do tell me if what you're trying to do works for you, cause last time there were complaints on fetch not working with proxy due it it not having an intercept for baseUrls, so I wanna know if I should make something for that.

That's really all I'm trying to do is to prepend the baseUrl to all HTTP requests, as given by an environment variable. The proxying part of it is really secondary to just wanting to not have to hardcore the URL in my client code.

**Comment by Teranode** [comment]
it's probably take a while for me to come up with a solution for that. But for now you could use something like this:

```ts
const { data: books } = await useAsyncData('books', async () => {
    const { data } = await $axios.$get('/api/books')
    return data
}, { initialCache: false })
```

it's what I use as iv'e ran into the same issues if I try to use the `$fetch` function.

**Comment by nathanchase** [comment]
Well, I just decided to avoid using ohmyfetch entirely for now, and created my own composable wrapper around $axios, and hardcoded the API URL like so in nuxt.config:
```
axios: {
    baseURL: 'https://my.api.com',
  },
```
No matter what if I try to use `process.env.BASE_URL` or `import.meta.env.BASE_URL` or any other mechanism to pull env vars into nuxt.config, they all fail either completely, or fail in production.

**Comment by lowbits** [comment]
you can also use something like this

/server/api/[...].ts

```
const config = useRuntimeConfig()
const baseURL = config.public.apiBaseUrl

export default defineEventHandler(async event => {
    const method = useMethod(event)
    const params = useQuery(event)
    const body = method === "GET" ? undefined : await useBody(event)

    return await $fetch(event.req.url, {
        headers: {
            "Content-Type": "application/json"
        },
        baseURL,
        method,
        params,
        body
    })
})
```
