### ISSUE TITLE
Proxy: Not working on windows

### ISSUE THREAD

**Issue by Caceresenzo** [Teranode/nuxt-module-alternatives#61]
The proxy module seems to try to load a rather strange file.

```
 WARN  'C:UsersusernameDesktopwebapp.nuxtserverProxy.ts' is imported by virtual:#internal/nitro/virtual/server-handlers, but could not be resolved – treating it as an external dependency
[worker reload] [worker init] Only URLs with a scheme in: file, data are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:'
```

The problem is that Window is using `\` (back-slash) for his paths, so the real path is: `C:\Users\username\Desktop\webapp\.nuxt\serverProxy.ts`.

Here lies the culprit:
https://github.com/Teranode/nuxt-module-alternatives/blob/31518bff1f69962827af0e0caa155d7777c7f68a/%40nuxtjs-alt/proxy/src/options.ts#L12

A quick fix could be (tested and 'working'):
```typescript
  // back-slash are causing problem, replace them with regular slash
  const joined = join(nuxt.options.buildDir, "serverProxy.ts").replaceAll('\\', '/')
  addServerHandler({
    // add the 'file:///' protocol
    handler: `file:///${joined}`,
    middleware: true
  });
```
I am sure there must be a better build-in or nuxt utility method to do something like this.

Even though after sending the correct path, he still refuses to load the file.
```
 WARN  'file:///C:/Users/username/Desktop/webapp/.nuxt/serverProxy.ts' is imported by virtual:#internal/nitro/virtual/s
erver-handlers, but could not be resolved – treating it as an external dependency
 ERROR  [worker reload] [worker init] Unknown file extension ".ts" for C:\Users\username\Desktop\webapp\.nuxt\serverPro
xy.ts
```

All of the file in the `.nuxt` directory are `.mjs` (aside from some type declaration that are still in `.d.ts`), maybe a flag is missing to tell nuxt to compile the file into a module?

**Comment by Teranode** [comment]
update and try again?

**Comment by Caceresenzo** [comment]
Thanks man, that is working perfectly!

I took a quick look at the commit. I could never have done that myself.
Glad someone as good as you is handling this project!
