### ISSUE TITLE
nuxt-auth not working with r7/r8 and latest pinia

### ISSUE THREAD

**Issue by lowbits** [Teranode/nuxt-module-alternatives#63]
I spend some time checking why `useCookie` is not working on SSR with nuxtjs-alt/auth, because of that I upgraded nuxt to the latest with provided hotfix from the nuxt team. r8. 

But now I'm getting this error:

`
Rollup error: Could not load node_modules/pinia/dist/pinia.mjs/dist/pinia.mjs (imported by .nuxt/dist/server/server.mjs): ENOTDIR: not a directory, open '/node_modules/pinia/dist/pinia.mjs/dist/pinia.mjs'
`
`Could not load ..../node_modules/pinia/dist/pinia.mjs/dist/pinia.mjs (imported by .nuxt/dist/server/server.mjs): ENOTDIR: not a directory, open '/.../node_modules/pinia/dist/pinia.mjs/dist/pinia.mjs'`

This error is gone when removing "@nuxtjs-alt/auth", "@nuxtjs-alt/axios" from modules in nuxt.config.ts

EDIT:
Now I had a deeper look, and it's looking like rollup is messing up `/dist/pinia.mjs/dist/pinia.mjs` duplicate `dist/pinia.mjs`, tried to fix it and provide a pr, but I'm not able to :D

**Comment by Teranode** [comment]
add:
```ts
    build: {
        transpile: [
            'pinia'
        ]
    },
```

to your nuxt config.

**Comment by lowbits** [comment]
thank you
