### ISSUE TITLE
use latest proxy version always return html!

### ISSUE THREAD

**Issue by KahrLu** [Teranode/nuxt-module-alternatives#67]
Hi @Teranode , **I think the latest version of proxy has a huge issue**

nuxt.rc3-8
@nuxtjs-alt/axios    1.0.16
@nuxtjs-alt/proxy     1.3.1
![image](https://user-images.githubusercontent.com/76502123/185542221-202c702c-d674-4ad0-b1a2-88a5a179eac5.png)

![image](https://user-images.githubusercontent.com/76502123/185540605-cbba2158-373f-4e15-9264-5a6374b6a31e.png)

looks like the response is html string of this project's homepage
![image](https://user-images.githubusercontent.com/76502123/185542003-353f681b-a327-448b-95f8-100baaa0c7bf.png)

**Comment by KahrLu** [comment]
**html code is :**

<!DOCTYPE html>\n<html data-head-attrs=\"\">\n

<head>
  <title></title>
  <meta charset=\"utf-8\">
  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">
  <meta name=\"head:count\" content=\"2\">
  <link rel=\"modulepreload\" as=\"script\" crossorigin href=\"/_nuxt/@vite/client\">
  <link rel=\"preload\" as=\"style\" href=\"/_nuxt/node_modules/element-plus/dist/index.css\">
  <link rel=\"preload\" as=\"style\"
    href=\"/_nuxt/node_modules/@nuxt/ui-templates/dist/templates/error-404.vue?vue&type=style&index=0&scoped=bc8852ab&lang.css\">
  <link rel=\"preload\" as=\"style\"
    href=\"/_nuxt/node_modules/@nuxt/ui-templates/dist/templates/error-dev.vue?vue&type=style&index=0&scoped=6b2d7187&lang.css\">
  <link rel=\"preload\" as=\"style\"
    href=\"/_nuxt/node_modules/@nuxt/ui-templates/dist/templates/error-500.vue?vue&type=style&index=0&scoped=f37408fc&lang.css\">
  <link rel=\"modulepreload\" as=\"script\" crossorigin
    href=\"/_nuxt/C:/Code/Test/nuxt-app/node_modules/nuxt/dist/app/entry\">
  <link rel=\"stylesheet\" href=\"/_nuxt/node_modules/element-plus/dist/index.css\">
  <link rel=\"stylesheet\"
    href=\"/_nuxt/node_modules/@nuxt/ui-templates/dist/templates/error-404.vue?vue&type=style&index=0&scoped=bc8852ab&lang.css\">
  <link rel=\"stylesheet\"
    href=\"/_nuxt/node_modules/@nuxt/ui-templates/dist/templates/error-dev.vue?vue&type=style&index=0&scoped=6b2d7187&lang.css\">
  <link rel=\"stylesheet\"
    href=\"/_nuxt/node_modules/@nuxt/ui-templates/dist/templates/error-500.vue?vue&type=style&index=0&scoped=f37408fc&lang.css\">
</head>\n

<body data-head-attrs=\"\">
  <div id=\"__nuxt\">
    <div><button class=\"el-button\" aria-disabled=\"false\" type=\"button\" style=\"\">
        
        
      </button></div>
  </div>
  <script>window.__NUXT__ = { data: {}, state: {}, _errors: {}, serverRendered: true, config: { public: {}, app: { baseURL: \"\\u002F\",buildAssetsDir:\"\\u002F_nuxt\\u002F\",cdnURL:\"\"}}}</script>
  <script type=\"module\" src=\"/_nuxt/@vite/client\" crossorigin></script>
  <script type=\"module\" src=\"/_nuxt/C:/Code/Test/nuxt-app/node_modules/nuxt/dist/app/entry\" crossorigin></script>
</body>\n

</html>

**Comment by Teranode** [comment]
can you provide a repro so i can take a look?
