### ISSUE TITLE
Example of TypeScript

### ISSUE THREAD

**Issue by steklopod** [Teranode/nuxt-module-alternatives#82]
Hi guys. Thank you for your work. I'm currently moving from `nuxt 2` to `nuxt 3` and I found your library.
I am new at `nuxt 3` and can't realize how to configure `nuxtjs-alt/auth`. 

Comunity will be happier if you provide any link with example.

I tried something like this, but it obviously is not working solution:

<img width="321" alt="Снимок экрана 2022-09-23 в 20 49 56" src="https://user-images.githubusercontent.com/29500153/192036906-b7d9d060-4d76-442f-aef4-b827ec622b92.png">
<img width="639" alt="Снимок экрана 2022-09-23 в 20 50 13" src="https://user-images.githubusercontent.com/29500153/192036943-994b9752-7cef-4088-930a-c0532679101c.png">

I am backender, so pls, don't be angry if it is stupid question

**Comment by Teranode** [comment]
You have to get `$auth` from `useNuxtApp`.

**Comment by steklopod** [comment]
Thank you for quick reply.
 I tried this, but it seems not to be typed. There are no suggestions from IDE:
<img width="953" alt="Снимок экрана 2022-09-24 в 11 49 51" src="https://user-images.githubusercontent.com/29500153/192091695-2711ae3c-7c1b-488a-991b-015ceb5a8b9d.png">

For example, in nuxt 2 project I have suggestions:
<img width="896" alt="Снимок экрана 2022-09-24 в 11 52 30" src="https://user-images.githubusercontent.com/29500153/192091751-8b9a74fe-be3c-4834-bd79-a48bf312d357.png">

**Comment by Teranode** [comment]
I've updated the package, try to see if that works for you, if not, also try using `const auth = useAuth()`

**Comment by steklopod** [comment]
Wow!  Thanks a lot! Now all suggestions are in place!
<img width="899" alt="Снимок экрана 2022-09-25 в 14 31 29" src="https://user-images.githubusercontent.com/29500153/192143512-30351e6c-d38d-4860-80e8-84f60347a45b.png">
