### ISSUE TITLE
Right way for passing request body into `loginWith`

### ISSUE THREAD

**Issue by steklopod** [Teranode/nuxt-module-alternatives#83]
I am trying to pass request body into:

```js
await this.$auth.loginWith('local', {data: this.userPrincipal})
```
And it's looks like the body is empty. This code is taken from working nuxt 2 project.

<img width="996" alt="Снимок экрана 2022-09-25 в 19 09 33" src="https://user-images.githubusercontent.com/29500153/192156131-5585a781-7052-44b2-b05c-ea0626343645.png">

My nuxt config:
<img width="555" alt="Снимок экрана 2022-09-25 в 19 10 32" src="https://user-images.githubusercontent.com/29500153/192156174-d52b441e-4403-4773-8fb7-77b42f40c325.png">

But if I change `data` to `body` it will work. 
```js
await this.$auth.loginWith('local', {body: this.userPrincipal})
```
Did I miss something? But there is no information about it...

I think it will be helpfull for other people in nuxt comunity who use your helpfull library

**Comment by Teranode** [comment]
I've mentioned in the readme about the changes for version 2.0+ going forward
![image](https://user-images.githubusercontent.com/1527149/192177549-142dd88e-4311-444b-9f48-f6f374f3914b.png)
