### ISSUE TITLE
OIDCSchema fails to request token error 415

### ISSUE THREAD

**Issue by maximilianmaihoefner** [Teranode/nuxt-module-alternatives#89]
When using the OIDCSchema with Keycloak I get an error after being redirected back to my Application:
POST http://localhost:8081/realms/localhost/protocol/openid-connect/token net::ERR_FAILED 415

This error occurs because the Token Request set a "content-type" header of "application/json". This is incorrect according to the OIDC Client Specification: https://openid.net/specs/openid-connect-basic-1_0.html#ObtainingTokens
According to the Spec one is supposed to send a "content-type" of "application/x-www-form-urlencoded". This can be achieved by changing the `#handleCallback` in [`auth/runtime/schemas/openIDConnect.ts`](https://github.com/Teranode/nuxt-module-alternatives/blob/master/@nuxtjs-alt/auth/src/runtime/schemes/openIDConnect.ts#L227) to send a URLSearchParams in the body instead of encoding it as json:
```ts
      const response = await this.$auth.request({
        method: "post",
        url: this.options.endpoints.token,
        baseURL: "",
        headers: {
          'content-type': 'application/x-www-form-urlencoded',
        },
        body: new URLSearchParams({
          code: parsedQuery.code,
          client_id: this.options.clientId,
          redirect_uri: this.redirectURI,
          response_type: this.options.responseType,
          audience: this.options.audience,
          grant_type: this.options.grantType,
          code_verifier: codeVerifier
        }).toString()
      });
```

If you want I can create a PR for this change.

I'm not sure if any other OIDC Providers support being sent a JSON, but Keycloak doesn't and if I understand the Spec correctly, a client is supposed to set "application/x-www-form-urlencoded". I'm not claiming to be an OIDC expert, i might be wrong and am open for other suggestions!

Versions used:
nuxt: 3.0.0-rc11
@nuxtjs-alt/auth: 2.0.16
@nuxtjs-alt/http: 1.3.3
Keycloak: 19.0.3

**Comment by Teranode** [comment]
Considering section 3.2 requires it to be `application/x-www-form-urlencoded`, I'll take a look at it later tonight.

My followup is, have you tested what you wrote in that code box.

**Comment by Teranode** [comment]
changes have been applied

**Comment by maximilianmaihoefner** [comment]
Yes the Code I posted was tested and worked for me and the latest Version (2.0.20) is also working for me now! Thank you for the quick update!
