### ISSUE TITLE
Nuxt Auth fetchUser always redirects to homepage

### ISSUE THREAD

**Issue by nfunwigabga** [Teranode/nuxt-module-alternatives#91]
Whenever I try to fetch the current user, the user is fetched successfully but there is always a redirect to the homepage.

try:
```javascript
const {$auth} = useNuxtApp()

onMounted(() => {
    $auth.fetchUser()
})
```

Regardless of which page I am on, I get redirected to the home page after I get the response.

Using 
```
"@nuxtjs-alt/auth": "^2.0.14",
"@nuxtjs-alt/http": "^1.3.14",
"@nuxtjs-alt/proxy": "^1.3.5",
"@pinia/nuxt": "^0.4.3"
```

**Comment by Teranode** [comment]
update to the latest version and try

**Comment by nfunwigabga** [comment]
This is fixed in the latest version. However, it seems to have introduced another minor issue... the user is not redirected away from the the login screen after login, even when `watchLoggedIn: true` is set in the configuration.

**Comment by Teranode** [comment]
I can reproduce this issue on my end.

**Comment by nfunwigabga** [comment]
Hmm. weird. I just installed everything on a fresh project and got the same result. No redirect after login. I have to manually do `navigateTo("/")`.

Here is how I set up the fresh install. Maybe I am missing something in the setup then? https://github.com/nfunwigabga/nuxt-auth-test

Everything else seems to be ok, including middleware etc.

**Comment by Teranode** [comment]
I suggest just manually redirecting after login then. This is low priority for me at the moment.

**Comment by nfunwigabga** [comment]
Yep, that's what I'm doing. And yes it's low priority really. 

For anyone looking, you may want to redirect the user the the `intended` URL  stored int he cookies on login. So this is what I'm doing:

```javascript
const redirectUrl = useCookie('auth.redirect', { default: () => "/"})
const {$auth}=useNuxtApp()

async function login(){
   try {
    await $auth.loginWith("local", {
      body: {email: "foo@bar.com", password: "password" },
    });
    navigateTo(redirectTo.value);
    redirectUrl.value = null; // clear the cookie on successful login
  } catch (error) {
    errors.value = error.data?.errors;
  }
}

```

Cheers!
