### ISSUE TITLE
Invalid path on Windows

### ISSUE THREAD

**Issue by HydrofinLoewenherz** [Teranode/nuxt-module-alternatives#93]
The http (or auth) module only seems to work on Linux. On Windows i get the following error message on application startup. On Linux it works.

`[worker reload] [worker init] Only URLs with a scheme in: file, data are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:'`

When i remove the http module, i don't get the error (but it doesn't authenticate). Similar to #61.

My modules:
```js
'@nuxtjs/tailwindcss',
'@nuxtjs-alt/auth',
'@nuxtjs-alt/http',
'@nuxtjs-alt/proxy', // needed if using ssr
[
  '@pinia/nuxt',
  {
    autoImports: [
      // automatically imports `defineStore`
      'defineStore', // import { defineStore } from 'pinia'
      // automatically imports `defineStore` as `definePiniaStore`
      ['defineStore', 'definePiniaStore'], // import { defineStore as definePiniaStore } from 'pinia'
    ],
  },
]
```

dependencies
```
"nuxt": "3.0.0-rc.11"
"@nuxtjs-alt/auth": "^2.0.19",
"@nuxtjs-alt/http": "^1.3.15",
"@nuxtjs-alt/proxy": "^1.3.4",
"@pinia/nuxt": "^0.4.3",
```

**Comment by Teranode** [comment]
That doesn't tell me what's being affected in the http module. I don't utilize modules in a windows environment for me to test them.

**Comment by HydrofinLoewenherz** [comment]
Thanks for the quick answer. I will take a deeper look into it myself.

**Comment by zaeval** [comment]
> Thanks for the quick answer. I will take a deeper look into it myself.

Did you solve it?

**Comment by HydrofinLoewenherz** [comment]
No sadly not. To get things done I decided to use a vue lib that i modified to work with nuxt and ssr. That works (more or less) for now. As soon as I have the time, I will have another look at this.
