### ISSUE TITLE
Keycloak oauth2 standard flow gives 415

### ISSUE THREAD

**Issue by HydrofinLoewenherz** [Teranode/nuxt-module-alternatives#94]
When using the following configuration, i get a HTTP 415.

```
keycloak: {
  scheme: 'oauth2',
  endpoints: {
    authorization: `${process.env.KEYCLOAK_HOST}/auth/realms/${process.env.KEYCLOAK_REALM}/protocol/openid-connect/auth`,
    token: `${process.env.KEYCLOAK_HOST}/auth/realms/${process.env.KEYCLOAK_REALM}/protocol/openid-connect/token`,
    userInfo: `${process.env.KEYCLOAK_HOST}/auth/realms/${process.env.KEYCLOAK_REALM}/protocol/openid-connect/userinfo`,
    logout: `${process.env.KEYCLOAK_HOST}/auth/realms/${process.env.KEYCLOAK_REALM}/protocol/openid-connect/logout`
  },
  token: {
    property: 'access_token',
    type: 'Bearer',
  },
  codeChallengeMethod: 'S256',
  scope: ['openid'],
  accessType: 'offline',
  responseType: 'code',
  clientId: process.env.KEYCLOAK_CLIENT_ID,
  grantType: 'authorization_code',
},
```

```
Access to fetch at 'https://xxx/auth/realms/xxx/protocol/openid-connect/token' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
POST https://xxx/auth/realms/xxx/protocol/openid-connect/token net::ERR_FAILED 415
```

I already checked, that localhost is a valid redirect url and web origin.

Similar to #89, but i already updated.
```
"nuxt": "3.0.0-rc.11"
"@nuxtjs-alt/auth": "^2.0.19",
"@nuxtjs-alt/http": "^1.3.15",
"@nuxtjs-alt/proxy": "^1.3.4",
"@pinia/nuxt": "^0.4.3",
```

**Comment by maximilianmaihoefner** [comment]
In #89 I was using the oidcSchema instead of the OAuth2 one, for me the `openIDConnect` Schema works with "@nuxtjs-alt/auth": "^2.0.20" and Keycloak 19.0.3. So you might want to try that instead as a workaround (it should just be replacing `oauth2` with `openIDConnect` in your Auth Config). I'm not familiar with the OAuth2 Spec but it might be that it also requires to send the data to the token endpoint as `application/x-www-form-urlencoded`.

**Comment by Teranode** [comment]
> In #89 I was using the oidcSchema instead of the OAuth2 one, for me the `openIDConnect` Schema works with "@nuxtjs-alt/auth": "^2.0.20" and Keycloak 19.0.3. So you might want to try that instead as a workaround (it should just be replacing `oauth2` with `openIDConnect` in your Auth Config). I'm not familiar with the OAuth2 Spec but it might be that it also requires to send the data to the token endpoint as `application/x-www-form-urlencoded`.

been looking at multiple api documentations regarding oauth2, and they all seem to use `application/x-www-form-urlencoded` when requesting an access token.
