### ISSUE TITLE
Redirects cause 'parentNode' of null error

### ISSUE THREAD

**Issue by toniengelhardt** [Teranode/nuxt-module-alternatives#96]
Scenario: I'm logged out and have some redirects defined like

```ts
auth: {
  globalMiddleware: true,
  redirect: {
    login: '/login',
    logout: '/login',
    callback: '/login',
    home: '/write',
  }
}
```

The login page has 

```
definePageMeta({
  layout: 'auth',
  auth: 'guest',
})
```

while the `/write` page uses the default layout.

When I try to load a page that is protected by auth, e.g. `/write` I'm correctly redirected, but get this error

<img width="1162" alt="Screen Shot 2022-10-17 at 17 28 52" src="https://user-images.githubusercontent.com/2703233/196232248-35a82bb2-8676-428c-b62e-a9eb37e2c774.png">

and the styles are messed up.

I can also see that the code in default layout `onMounted` is executed before the redirect, which should  not be the case, aka. the `/write` page should not be mounted at all right?

**Comment by zaeval** [comment]
Could you tell me about the version of nuxt that you are using and the environment?

**Comment by zaeval** [comment]
And in my case, global Middleware has a lot of problems, so I don't use it, but I usually use it by inserting the source code from a file in pages/*. Eventually, it also runs isLoggedIn on the server side, so it works the same way as middleware.

```js
if($auth.isLoggedIn)
    router.push({name:''});
```

**Comment by toniengelhardt** [comment]
@zaeval thanks for taking a look!

I'm using the latest `nuxt-edge` version, currently  `nuxt@3.0.0-rc.13-27768654.09e5534` with ` ssr:  false`.

```ts
modules: [
    // ...
    '@nuxtjs-alt/auth',
    '@nuxtjs-alt/http', // Needed for alt auth.
    // ...
]
```

I also have this global middleware: 

```ts
export default defineNuxtRouteMiddleware((to, from) => {
  if (to.path === '/') {
    return navigateTo('/write', { redirectCode: 301 })
  }
})
```

Not sure if that interferes somehow?
