### ISSUE TITLE
Svg Sprite Module

### ISSUE THREAD

**Issue by fedeweb** [Teranode/nuxt-module-alternatives#98]
Hi,

I have an issue with the svg sprite module.

In the config file I imported it in this way:

`export default defineNuxtConfig({
  typescript: {
		shim: false
	},
  modules: [
    'nuxt-purgecss','@nuxtjs-alt/svg-sprite'
  ]
})`

If I use the svg-icon component then I have this error:

`<svg-icon name="people" />`

_Uncaught (in promise) ReferenceError: useNuxtApp is not defined
    at setup (SvgIcon.vue:10:24)_
    
   
I'm using Nuxt 3 rc.11

Thanks,
Federico

**Comment by fedeweb** [comment]
Hi @Teranode,

I'm sorry to bother you. Do you need a reproduction from me? I thought the tag "needs-reproduction" meant that you need to reproduce the bug :)

Thanks,

Federico

**Comment by Teranode** [comment]
Yes I need a reproduction from you.

**Comment by fedeweb** [comment]
Hi @Teranode,

you can see here the issue:

https://stackblitz.com/edit/nuxt-3-windicss-nyyq12?file=app.vue

Thanks,

Federico

**Comment by Teranode** [comment]
you should probably use: https://github.com/nuxt-community/svg-sprite-module/tree/nuxt3
I was unaware they had worked on a nuxt3 module at the time.
